# Generated by Django 5.1.6 on 2025-02-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='statue_text',
            new_name='status_text',
        ),
    ]
